// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package udpbpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadUdp returns the embedded CollectionSpec for udp.
func loadUdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load udp: %w", err)
	}

	return spec, err
}

// loadUdpObjects loads udp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*udpObjects
//	*udpPrograms
//	*udpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// udpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpSpecs struct {
	udpProgramSpecs
	udpMapSpecs
}

// udpSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpProgramSpecs struct {
	XdpFilterPort *ebpf.ProgramSpec `ebpf:"xdp_filter_port"`
}

// udpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	XsksMap *ebpf.MapSpec `ebpf:"xsks_map"`
}

// udpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpObjects struct {
	udpPrograms
	udpMaps
}

func (o *udpObjects) Close() error {
	return _UdpClose(
		&o.udpPrograms,
		&o.udpMaps,
	)
}

// udpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	XsksMap *ebpf.Map `ebpf:"xsks_map"`
}

func (m *udpMaps) Close() error {
	return _UdpClose(
		m.Events,
		m.XsksMap,
	)
}

// udpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpPrograms struct {
	XdpFilterPort *ebpf.Program `ebpf:"xdp_filter_port"`
}

func (p *udpPrograms) Close() error {
	return _UdpClose(
		p.XdpFilterPort,
	)
}

func _UdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed udp_bpfeb.o
var _UdpBytes []byte
